sudo: true
language: node_js
node_js:
  - "6"
install:
  - sudo pip install mkdocs python-markdown-math
  - npm install -g bower gulp
before_script: wget https://raw.githubusercontent.com/UVicNotes/UVicNotes/master/scripts/deploy.sh
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/UVicNotes/CSC-370.git
  - secure: SRF4uOZs6rGHe/lRNO7qyhSIO8oP7ZhjY4oQvluM9YKvD5Fp1INEcpNVuhBgQes9qlY8o9w2S/SInvKk7JeEGqn2Df6dTufr2MBMOsU2QcLOvPvGoNXgi/fc52IZv980awzY3+JpB8QmdnA4wiuUKb1tBGgMhq0OIrMTnmdj6W60aRei2e5oTXL9XiMojG4f2MVA5yxnZeSABENz5TB+UpMOgEqSNOm3NSp4739IYtU82Tr/LN2Eu1na5nNdOhPEr/b7m4+BvPtF62rzU1mA7U5RgIlNa5UOaLuP8L2l7A6+aUSdkjOBoSi28Js2o20VdTVen09hUDPxZF4eqra7UeMTJY9c7LuTYJPK8H5vvsd12TaJEIcAwAjlSTYSp3gAyKOWM3L5YsWt+KaZn2nEvLSV+OkC1FQwg39EyU2LNfBDQaFdzxoLcBpLhAqwXo4TeZecVglgAEe+vB5mvEgg1Gfoiw9AblZvj1kSZ9Dl7OPdijCeJzHNWoJmoLZQ8DkPX8N/XEjODIA2SPIh3w85jB27eJM4IkQG9255e2HcacB8ZzTtKfW6cRbNyyve6GETuciCOb2rPXqQyyTxSVqLonHMWgfKKLf6ciTccg/mm8xk4fMa53WGseyYd68sVD1z1kYwHSoq/hHh0iOpPKtRk89hUvFPTiFhajSr+e9+wnk=
