site_name: CSC 370
docs_dir: Notes
theme_dir: theme
site_url: http://uvicnotes.github.io/CSC-370/
repo_url: https://github.com/UVicNotes/CSC-370
site_description: Course Notes for CSC 370 - Foundations of Computer Science
site_author: Brynn Hawker
google_analytics:
  - 'UA-91401009-1'
  - 'auto'
pages:
- Home: 'index.md'
- Notes:
    - 'Introduction': '1-Introduction.md'
    - 'Entity/Relationship Model': '2-Entity-Relationship-Model.md'
    - 'E/R Diagrams to Relations': '3-ER-diagrams-and-Relations.md'
    - 'Structured Query Language': '4-SQL.md'
    - 'Relational Algebra': '5-Relational-Algebra.md'
    - 'Functional Dependencies': '10-Functional-Dependencies.md'
extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://cdn.rawgit.com/UVicNotes/UVicNotes/81099952ba789829fab1840e5d26cb5a2bf62011/helpers/mathjax.js
markdown_extensions:
    - mdx_math
    - mdx_del_ins
    - codehilite(css_class=code)
    - admonition
    - smarty
    - toc:
        permalink: True
extra:
  version: 'Spring 2017'
  palette:
    primary: 'blue'
    accent: 'orange'
  author:
    github: 'UVicNotes'