site_name: CSC 370
docs_dir: Notes
site_url: http://uvicnotes.github.io/CSC-370/
repo_url: https://github.com/UVicNotes/CSC-370
site_description: Course Notes for CSC 370 - Foundations of Computer Science
site_author: Brynn Hawker
extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://cdn.rawgit.com/UVicNotes/UVicNotes/81099952ba789829fab1840e5d26cb5a2bf62011/helpers/mathjax.js
markdown_extensions:
    - mdx_math
theme: 'material'
extra:
  logo: 'images/UVicNotes-Logo.svg'
  palette:
    primary: 'cyan'
    accent: 'orange'
  font:
    text: 'Source Sans Pro'
    code: 'Source Code Pro'
  author:
    github: 'UVicNotes'